name: voila
channels:
  - conda-forge
dependencies:
  - python=3.12
  - ipywidgets=7.7.2
  - ipykernel
  - pandas
  - pip
  - bokeh
  - bqplot
  - ipympl=0.9.2
  - jupyterlab
  - jupyterlab-widgets
  - matplotlib
  - scipy
  - vega_datasets
  - ipyvolume
  - leafmap
  - pygis
  - maplibre
  - voila
  - voila_topbar

  - pip:
    - voila==0.5.0
    - voila-topbar==0.1.1
