name: voila
channels:
  - conda-forge
dependencies:
  - python==3.12
  - ipywidgets==8.1.1
  - ipykernel
  - pandas
  - pip
  - bokeh
  - bqplot
  - ipympl==0.9.2
  - jupyterlab
  - jupyterlab_widgets==3.0.9
  - widgetsnbextension==4.0.9
  - matplotlib
  - scipy
  - vega_datasets
  - ipyvolume
  - leafmap
  - maplibre
  - pygis
  - maplibre
  - voila
  - voila_topbar
  - geemap
  - solara

  - pip:
    - voila==0.5.5
    - voila-topbar==0.1.1
